[tool.mypy]
python_version = 3.6
ignore_missing_imports = true
strict_optional = true

[tool.black]
line-length = 120
exclude = '''
    .git,
    .mypy_cache
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
